### ISSUE TITLE
memo

### ISSUE THREAD

**Issue by yuuki00682200** [kojake/chat_gpt_request#1]
ファイル名を全て「main.py」にしていますが、しっかり命名するとなお良いです🙆‍♂️
それこそ、chatGPTに相談しているのであれば、「このプログラムを書いているのですが、Pythonファイルにはどのように名前をつけたら良いですか」と聞いてみましょう。

ファイル名・変数・関数などの命名について、プロジェクト的にプログラムを進める中で重要になってくるポイントなので✅

https://zenn.dev/takahiroinoway/books/30510b7bc78514/viewer/49dbe9

こういう記事がおすすめです

**Comment by kojake** [comment]
参考にします
